# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 556908a9741e93ac7b955ff049d78388c02bb9783589d3827a78110337e2919d763139cd016d8b71500f99f2f376e65ee3e747ad4e2333cf411893b4c949bf0a

test:
  secret_key_base: 4ee1d03b3a29acb480a52fcd9f0bb904eeec01db8f543ce22197495dab305e4c7e7d7c17fc32f272fad441a90b46e70c17b21baa0117683dfc57c95bf0d38fdd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
